openapi: 3.0.0

info:
  title: Cronos REST API
  description: This is a REST API application made with Express
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Development server

tags:
  - name: category
    description: Everything about Categories

paths:
  /category:
    get:
      tags:
        - category
      summary: Returns a list of categories.
      parameters:
        - name: name
          in: query
          description: Category name
          required: false
          schema:
            type: string
      responses:
        "200":
          description: A JSON array of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
        "default":
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - category
      summary: Create a category.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  description: Category name
      responses:
        "200":
          description: Created
        "default":
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /category/{id}:
    get:
      tags:
        - category
      summary: Returns a category by ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        "default":
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - category
      summary: Update a category by ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  description: Category name
      responses:
        "200":
          description: Updated
        "default":
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - category
      summary: Delete a category by ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Deleted
        "default":
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Category:
      required:
        - _id
        - name
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Error:
      type: object
      properties:
        message:
          type: string