name: Say Hello

on:
  push:
    branches:
      - master

jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo the message
        run: echo "Hello World"
      - name: Get the date
        run: date
      - run: ls -l