name: Deploy App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  avoid_redundancy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: supercharge/mongodb-github-action@1.7.0
        with:
          node-version: 5.0
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test

  deploy:
    needs:
        - test
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: https://${{secrets.HEROKU_APP}}.herokuapp.com/healthcheck
          rollbackonhealthcheckfailed: true